@prodApiUrl = https://api.tcup.cz
@devApiUrl = http://localhost:5000

@apiUrl = {{devApiUrl}}

@email = harasta.ivan@gmail.com
@password = harasta
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkM2Q3ZTBjYjQ3ZDdmMWQ0ODFkYzMyZiIsImlhdCI6MTU5MzY5MzEyNSwiZXhwIjoxNTkzNjk2NzI1fQ.vYLc6TBDuPci9j8xESOTw4pgVFF03xTK3Rl4oKZVa1k

POST {{apiUrl}}/api/auth
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}

###

GET {{apiUrl}}/api/news

###

GET {{apiUrl}}/api/regions

###

POST {{apiUrl}}/api/regions
Content-Type: application/json
x-auth-token: {{token}}

{
    "name": "Rakousko"
}

###

POST {{apiUrl}}/api/news
Content-Type: application/json
x-auth-token: {{token}}

{
    "title": "Test title",
    "body": "asdasd\nasdasd\nas\ndas\nda\nsd",
    "email": false
}

###

GET {{apiUrl}}/api/days

###

POST {{apiUrl}}/api/days
Content-Type: application/json
x-auth-token: {{token}}

{
    "name": "Den 4",
    "date": "2020-07-14"
}

###

PUT {{apiUrl}}/api/days/5efce7ee3de5543176239dc4
Content-Type: application/json
x-auth-token: {{token}}

{
    "task": "TASK_CANCELLED"
}

###

GET {{apiUrl}}/api/competitorstatuses/5efce7a13de5543176239dc2
Content-Type: application/json

###

POST {{apiUrl}}/api/competitorstatuses
Content-Type: application/json
x-auth-token: {{token}}

{
    "day": "5efce7a13de5543176239dc2"
}

###

PUT {{apiUrl}}/api/competitorstatuses/5efddb249ab08b63b090ed04
Content-Type: application/json
x-auth-token: {{token}}

{
    "status": "HOME"
}

###

GET {{apiUrl}}/api/igc/form
Content-Type: application/json
