@prodApiUrl = https://api.tcup.cz
@devApiUrl = http://localhost:5000

@apiUrl = {{devApiUrl}}

@email = harasta.ivan@gmail.com
@password = harasta
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkM2Q3ZTBjYjQ3ZDdmMWQ0ODFkYzMyZiIsImlhdCI6MTU5MzYzMjYwOCwiZXhwIjoxNTkzNjM2MjA4fQ.mCcMu5O8EdLsLXA3J00zH22eSxZr_U0WD-gpr8NLsKk

POST {{apiUrl}}/api/auth
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}

###

GET {{apiUrl}}/api/news

###

GET {{apiUrl}}/api/regions

###

POST {{apiUrl}}/api/regions
Content-Type: application/json
x-auth-token: {{token}}

{
    "name": "Rakousko"
}

###

POST {{apiUrl}}/api/news
Content-Type: application/json
x-auth-token: {{token}}

{
    "title": "Test title",
    "body": "asdasd\nasdasd\nas\ndas\nda\nsd",
    "email": false
}

###

GET {{apiUrl}}/api/days

###

POST {{apiUrl}}/api/days
Content-Type: application/json
x-auth-token: {{token}}

{
    "name": "Den 4",
    "date": "2020-07-14"
}

###

PUT {{apiUrl}}/api/days/5efce7ee3de5543176239dc4
Content-Type: application/json
x-auth-token: {{token}}

{
    "task": "TASK_CANCELLED"
}

