@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YTJmYWJjZGQ1MDVjMDAxODcwMWFmMSIsImlhdCI6MTc1Mjk5ODI2MCwiZXhwIjoxNzUzMDAxODYwfQ.gVCElIQ_LA02OIKNxGWVQu1fPHw7D_Jplm75JzDe7Lg

###

POST {{apiUrl}}/api/auth
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}

###

GET {{apiUrl}}/api/news

###

GET {{apiUrl}}/api/regions

###

POST {{apiUrl}}/api/regions
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Rakousko"
}

###

POST {{apiUrl}}/api/news
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Test title",
    "body": "asdasd\nasdasd\nas\ndas\nda\nsd",
    "email": false
}

###

GET {{apiUrl}}/api/days

###

POST {{apiUrl}}/api/days
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Den 4",
    "date": "2025-07-20"
}

###

PUT {{apiUrl}}/api/days/5efce7ee3de5543176239dc4
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "task": "TASK_CANCELLED"
}

###

GET {{apiUrl}}/api/competitorstatuses/687ca19aea224a0015318830
Content-Type: application/json

###

POST {{apiUrl}}/api/competitorstatuses
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "day": "687ca19aea224a0015318830"
}

###

PUT {{apiUrl}}/api/competitorstatuses/5efddb249ab08b63b090ed04
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "status": "HOME"
}

###

GET {{apiUrl}}/api/igc/form
Content-Type: application/json

###

GET {{apiUrl}}/api/classes
Content-Type: application/json

###

GET {{apiUrl}}/api/tracking/687ca19aea224a0015318830
Content-Type: application/json

###

POST {{apiUrl}}/api/tracking/687ca19aea224a0015318830/6403c053c223c102ea1f60a1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "label": "Tracking Klub Day 4",
    "taskUrl": "https://www.soaringspot.com/en_gb/tcup2025/tasks/klub/task-3-on-2025-07-20"
}

###

GET {{apiUrl}}/api/starting-list/export/seeyou/5d4026c05fa77179689ce31c
Authorization: Bearer {{token}}

###

GET {{apiUrl}}/api/igc/5efce7a13de5543176239dc2
Authorization: Bearer {{token}}

###

PUT {{apiUrl}}/api/igc/5f09a7ed72acfb0f2c35f3ba
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "processed": true,
    "downloaded": true
}